import {randomBytes,randomUUID,scryptSync,timingSafeEqual} from 'node:crypto';
const hash=password=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`;};
const verify=(password,value)=>{const [salt,digest]=value.split(':');const expected=Buffer.from(digest,'hex'),actual=scryptSync(password,salt,64);return expected.length===actual.length&&timingSafeEqual(expected,actual);};
export const safeUser=u=>u?{id:u.id,name:u.name,email:u.email,role:u.role}:null;
export function initializeUsers(db){if(db.users)return;db.users=[{id:'user-admin',name:'Demo Admin',email:'admin@example.com',role:'admin',passwordHash:hash(process.env.ADMIN_PASSWORD||'Admin123!')},{id:'user-customer',name:'Demo Customer',email:'customer@example.com',role:'customer',passwordHash:hash(process.env.CUSTOMER_PASSWORD||'Customer123!')}];}
const sessions=new Map();
export function currentUser(req,db){const token=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('shop_session='))?.slice(13);const s=sessions.get(token);if(!s||s.expires<Date.now()){sessions.delete(token);return null;}return db.users.find(u=>u.id===s.userId)||null;}
export function login(email,password,db,res){const u=db.users.find(u=>u.email===String(email).trim().toLowerCase());if(!u||typeof password!=='string'||password.length>200||!verify(password,u.passwordHash))return null;const token=randomBytes(32).toString('hex');sessions.set(token,{userId:u.id,expires:Date.now()+12*60*60*1000});res.setHeader('Set-Cookie',`shop_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200`);return safeUser(u);}
export function logout(req,res){const token=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('shop_session='))?.slice(13);sessions.delete(token);res.setHeader('Set-Cookie','shop_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');}
export function register(b,db){if(typeof b.name!=='string'||!b.name.trim()||typeof b.email!=='string'||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email)||typeof b.password!=='string'||b.password.length<8||b.password.length>200)return {error:'Name, valid email, and a password of 8–200 characters are required'};const email=b.email.trim().toLowerCase();if(db.users.some(u=>u.email===email))return {error:'An account with that email already exists'};const u={id:randomUUID(),name:b.name.trim(),email,role:'customer',passwordHash:hash(b.password)};db.users.push(u);return {user:safeUser(u)};}
