import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import http from 'node:http';
const dir=mkdtempSync(path.join(tmpdir(),'larkspur-test-'));
const base='http://127.0.0.1:3107';let processHandle,webhook,received=[];
async function request(p,method='GET',body,headers={}){const r=await fetch(base+'/api'+p,{method,headers:{'content-type':'application/json','x-api-key':'test-automation-key',...headers},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
const payload=(productId='ceramic-vase',quantity=1,paymentStatus='authorized')=>({customer:{name:'Demo Tester',email:'tester@example.com',address:'12 Test Street, Tunis'},shippingAddress:{street:'12 Test Street',city:'Tunis',postal_code:'1000',country:'TN'},items:[{productId,quantity}],paymentStatus});
const act=(id,a,b={})=>request(`/orders/${id}/${a}`,'POST',b);
before(async()=>{processHandle=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3107',DATA_DIR:dir,API_KEY:'test-automation-key',N8N_WEBHOOK_URL:''},stdio:'ignore'});for(let i=0;i<60;i++){try{if((await request('/health')).status===200)break;}catch{}await new Promise(r=>setTimeout(r,100));}assert.equal((await request('/health')).status,200);webhook=http.createServer(async(req,res)=>{let b='';for await(const c of req)b+=c;received.push(JSON.parse(b));res.writeHead(received.length===1?500:200);res.end('fixture');});await new Promise(r=>webhook.listen(3108,'127.0.0.1',r));});
after(async()=>{processHandle.kill();await new Promise(r=>processHandle.once('exit',r));await new Promise(r=>webhook.close(r));rmSync(dir,{recursive:true,force:true});});
test('validates customer data and calculates prices on the server',async()=>{assert.equal((await request('/orders','POST',{})).status,400);const {data:o}=await request('/orders','POST',{...payload(),total:1});assert.equal(o.total,44);assert.equal(o.status,'received');});
test('idempotent full workflow reserves once and requires physical checklist',async()=>{const {data:o}=await request('/orders','POST',payload('oak-stool'),{'idempotency-key':'one-order'});assert.equal((await request('/orders','POST',payload('oak-stool'),{'idempotency-key':'one-order'})).data.id,o.id);assert.equal((await act(o.id,'ship')).status,409);await act(o.id,'validate');await act(o.id,'confirm');await act(o.id,'reserve');await act(o.id,'reserve');assert.equal((await request('/products')).data.find(p=>p.id==='oak-stool').stock,3);assert.equal((await act(o.id,'warehouse',{status:'ready'})).status,400);await act(o.id,'warehouse',{status:'ready',checklist:{picked:true,verified:true,packed:true}});const s=await act(o.id,'ship');assert.match(s.data.shipment.trackingNumber,/^DEMO-/);assert.equal((await act(o.id,'ship')).data.shipment.trackingNumber,s.data.shipment.trackingNumber);assert.equal((await act(o.id,'cancel')).status,409);await act(o.id,'delivery',{status:'delivered'});assert.equal((await act(o.id,'delivery',{status:'delayed'})).status,409);assert.equal((await act(o.id,'reconcile')).data.payment.status,'settled');});
test('failed payments require review and cannot reserve inventory',async()=>{const {data:o}=await request('/orders','POST',payload('coffee-set',1,'failed'));assert.equal((await act(o.id,'validate')).data.status,'needs_review');assert.equal((await act(o.id,'reserve')).status,409);});
test('insufficient stock makes no partial deduction; cancellation restores stock once',async()=>{const stock=(await request('/products')).data.find(p=>p.id==='ceramic-vase').stock;const {data:o}=await request('/orders','POST',{...payload(),items:[{productId:'ceramic-vase',quantity:1},{productId:'serving-bowl',quantity:1}]});assert.equal((await act(o.id,'validate')).data.status,'needs_review');assert.equal((await act(o.id,'confirm')).status,409);assert.equal((await request('/products')).data.find(p=>p.id==='ceramic-vase').stock,stock);const {data:c}=await request('/orders','POST',payload());await act(c.id,'validate');await act(c.id,'confirm');await act(c.id,'reserve');await act(c.id,'cancel');await act(c.id,'cancel');assert.equal((await request('/products')).data.find(p=>p.id==='ceramic-vase').stock,stock);});
test('support records are stored and can be escalated',async()=>{const {data:t,status}=await request('/support','POST',{email:'demo@example.com',message:'Please connect me with a human.'});assert.equal(status,201);assert.equal((await request('/support/'+t.id,'PATCH',{status:'escalated'})).data.status,'escalated');});
test('support persists, reconstructs, and triages the full conversation thread',async()=>{const {data:t,status}=await request('/support','POST',{email:'thread@example.com',message:'I need help with my order.'});assert.equal(status,201);assert.equal(t.messages.length,1);assert.ok(t.threadId);await request(`/support/${t.id}/messages`,'POST',{message:'The package is missing and this is urgent.'});const {data:context}=await request(`/automation/support/${t.id}/context`);assert.equal(context.messages.length,2);assert.match(context.transcript,/CUSTOMER.*I need help/);assert.match(context.transcript,/STAFF.*package is missing/);const triaged=await request(`/automation/support/${t.id}/triage`,'POST',{thread_id:context.thread_id,transcript:context.transcript,message_count:context.messages.length});assert.equal(triaged.data.threadReconstructed,true);assert.equal(triaged.data.messageCount,2);assert.equal(triaged.data.priority,'high');assert.equal(triaged.data.category,'delivery');const stored=(await request('/support')).data.find(x=>x.id===t.id);assert.equal(stored.triage.threadSummary.startsWith('2 messages'),true);});
test('failed webhook can be replayed with stable event ID',async()=>{await request('/settings','PATCH',{webhookUrl:'http://127.0.0.1:3108/events'});const {data:o}=await request('/orders','POST',payload());let e;for(let i=0;i<40;i++){e=(await request('/events')).data.find(e=>e.order?.id===o.id);if(e.delivery.status==='failed')break;await new Promise(r=>setTimeout(r,50));}assert.equal(e.delivery.status,'failed');assert.equal((await request(`/events/${e.id}/retry`,'POST',{})).data.delivery.status,'delivered');assert.equal(received[0].id,received[1].id);assert.equal(received[0].type,'order.created');assert.equal(received[0].baseUrl,'http://localhost:3107');});
test('included workflow routes lifecycle events and ignores its own updates',()=>{const workflow=JSON.parse(readFileSync('n8n/larkspur-order-workflow.json','utf8'));const choose=new Function('$input',workflow.nodes.find(n=>n.type==='n8n-nodes-base.code').parameters.jsCode);for(const [type,action] of [['order.created','validate'],['order.confirmed','reserve'],['warehouse.ready','ship'],['shipment.updated','reconcile']]){const result=choose({first:()=>({json:{body:{id:'event-id',type,baseUrl:'http://demo',order:{id:'LC-1001',shipment:{status:'delivered'}}}}})});assert.equal(result[0].json.url,`http://host.docker.internal:3000/api/orders/LC-1001/${action}`);}assert.deepEqual(choose({first:()=>({json:{body:{type:'payment.reconciled'}}})}),[]);});
test('payment reconciliation replay creates no additional events',async()=>{const o=(await request('/orders')).data.find(o=>o.status==='delivered');const before=(await request('/events')).data.length;await act(o.id,'reconcile');assert.equal((await request('/events')).data.length,before);});

